# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5caaa6e060b186b52e9e58244bca23b3710dc54af66448922d81d5e37edc1f7bdcbd9bd929e1b58e75779249449cf8048df48eb51d28d1ecd1d6eba84d451b54

test:
  secret_key_base: 50cbb325eba9d00d8f151eb96b5f06628bac6b025b88fca2a90c7e9a7c0c54efc95debac4e4d1f41ba647379bbd30d9c8dedabe1d3c51f886aa4f97e28db827a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
